spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: ${db.url}
      database: ${db.name}
