spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.user}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: ${db.url}
      database: ${db.name}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapi.com/oauth2/v3/certs

jwt:
  secret: ${jwt.secret}
